### ISSUE TITLE
Översikt för vilka som förtjänar hederstecken

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#125]
Det skulle underlätta Medaljelelekommiténs arbete om det fanns något sätt att se vilka som bör tilldelas vilka hederstecken.
Detta borde i allmänhet gå att göra med rätt simpla queries:

-   **Funktionärsmedalj:** Alla som hade ett mandat förra året
-   **Gammal && Äcklig:** De som har haft mandat i styrelsen och mandat i tre år eller längre OCH de som har haft mandat i fyra år eller längre.
-   **Styrelsemedalj:** De som hade ett mandat i styrelsen förra året och inte ett tidigare år.
-   **Utskottsmedalj?:** Hur de nu var definierade. Om de ens finns/fanns? Mandelaeffekten intensifierar.

**Comment by danieladugyan** [comment]
Låter som en rimlig idé, men tyvärr är det inte uppenbart för mig i nuläget hur denna funktion skulle kunna utformas. Din första query är ju simpel men de andra är mer invecklade. En enkel lösning skulle kunna vara att hårdkoda exakt de filter du efterfrågar, men inget annat. Om det krävs mer flexibilitet, t.ex. ett textfält som tillåter godtyckliga queries, så vet jag inte riktigt om det är något vi kan genomföra.

**Comment by fnurkla** [comment]
Ja, min tanke var just att man hårdkodade dem här. Det här är ju inte heller någon jätteprio i mina ögon utan mer nice to have.
