### ISSUE TITLE
Update your information form not screen-size responsive

### ISSUE THREAD

**Issue by Isak-Kallini** [Dsek-LTH/web#155]
When editing your information (name, programme etc.) on you profile page the form goes offscreen on small screen sizes. 
![bild](https://github.com/Dsek-LTH/web/assets/65332998/9991014e-38cc-4932-9456-1b20ab648c85)

**Comment by AnukratiMehta** [comment]
@Isak-Kallini 

Hello, I'd like to work on this. Please assign it. Thanks!

**Comment by AnukratiMehta** [comment]
@Isak-Kallini 

I want to get the local copy up and running and the README mentions this: 

```3. Setup .env.local by copying .env and filling in the values (ask a team member for credentials).```

Please share the same.

**Comment by Isak-Kallini** [comment]
It's probably not needed since the credentials are for the Minio server which is used for files (meeting documents etc.), but I'll dm you on discord.

**Comment by AnukratiMehta** [comment]
> It's probably not needed since the credentials are for the Minio server which is used for files (meeting documents etc.), but I'll dm you on discord.

Thanks! Here's my [Discord profile](https://discordapp.com/users/1014475849736671263).

**Comment by Isak-Kallini** [comment]
I thought that you were someone else because of irl circumstances and not looking too closely at your profile, so I can't give you the credentials. It should not be required for this issue though, so feel free to work on it.

**Comment by AnukratiMehta** [comment]
No worries, @Isak-Kallini. I was asking because I'm facing this error when I try to run the application: 

Error: P1010: User `postgres` was denied access on the database `dsek.public`.

I haven't contributed to a lot of projects yet. Can you help me figure out what may be causing this? 
For context, I followed the instructions on your README to run the application. Thanks!

**Comment by Isak-Kallini** [comment]
I'm unsure, if you google the error message you'll find a lot of people having a similar issue with a lot of different solutions. Have you used postgres before? It seems like it could be another instance running on it's own that's interfering. https://www.github.com/remix-run/blues-stack/issues/49
