### ISSUE TITLE
Korta utskottsbeskrivningar på dsek.se/committees/

### ISSUE THREAD

**Issue by anahitachavan** [Dsek-LTH/web#163]
Alltså på sidan där man ser alla utskottsloggor. Så att folk får en aning om vad ett utskott gör och inte behöver trycka på varenda utskott om de letar efter en specifik typ av utskott.

**Comment by danieladugyan** [comment]
Finns redan!

**Comment by anahitachavan** [comment]
> Finns redan!

Inte på första sidan för alla utskott?
