### ISSUE TITLE
Add Jenkinsfile

### ISSUE THREAD

**Issue by Isak-Kallini** [Dsek-LTH/web#186]
https://www.jenkins.io/doc/book/pipeline/jenkinsfile/
https://medium.com/@systemglitch/continuous-integration-with-jenkins-and-github-release-814904e20776

**Comment by fnurkla** [comment]
We technically have one now. Did we come to a conclusion about what, if anything, should be done in Jenkins instead of GH actions?

**Comment by Isak-Kallini** [comment]
I think we will be doing deployments with Jenkins, but we're not doing anything in Jenkins right now.

**Comment by Isak-Kallini** [comment]
closed by #283
