### ISSUE TITLE
Add slugs to old events

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#192]
A lot of old events are missing slugs. This is problematic as it is then impossible to visit their page to read about them. In the test data, only 259 of the 2381 events actually have a slug.

**Comment by alfredgrip** [comment]
I guess we could do something like we did with songs: https://github.com/Dsek-LTH/web/blob/dee5c9983d638e9ba4fa9450b7a68ffb197e503d/src/database/prisma/migrations/20240115231946_add_song_slug_and_deleted_at/migration.sql

**Comment by Macludde** [comment]
I think this is fixed. Or at least, if an event is missing a slug you can link to dsek.se/events/id/[id] and the route will automatically create a slug and then redirect the client
