### ISSUE TITLE
The "Inloggad som" dropdown shows the wrong full name when visiting somebody elses profile

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#194]
If you visit somebody else's profile when logged in and you press the button in the top right corner, it will display the full name of the user whose profile you are visiting instead of your own. As an example:
![image](https://github.com/Dsek-LTH/web/assets/97372888/a88e560b-52eb-40fa-84aa-082ef9900bde)

**Comment by danieladugyan** [comment]
@alfredgrip You're already working on this, right?

**Comment by alfredgrip** [comment]
> @alfredgrip You're already working on this, right?

Not actively no. I can give it a shot though!
