### ISSUE TITLE
Kunna se folks dsek-mailadresser på deras profiler

### ISSUE THREAD

**Issue by johannesnydahl** [Dsek-LTH/web#219]
Tjena!

Tänkte att det skulle vara bra ifall medlemmarnas dsek-mailadresser står på deras profilsidor. Både för att man i så fall enkelt kan kontakta varandra, men också för uppmärksamma medlemmarna om att de faktiskt har en egen dsek-mail och vilken adress de har. Det kan likna lite hur man på nuvarande hemsidan kan se medlemmarnas mail-aliaser, ifall de har en post på sektionen.

**Comment by danieladugyan** [comment]
Låter som en bra idé!

**Comment by danieladugyan** [comment]
@Dsek-LTH/dwww Observera att man på den nya sidan varken kan se mail-alias eller ens privata dsek-mail. Båda dessa delar måste fixas.
