### ISSUE TITLE
Booking admin interface is missing "Responsible person" field

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#222]
Old:
![Image](https://github.com/Dsek-LTH/web/assets/26229521/e84378e1-66e6-48f0-aa55-f50e818cb7ea)

New:
![Image](https://github.com/Dsek-LTH/web/assets/26229521/9c466933-3907-4fa9-b081-d2617c312a9d)

**Comment by fnurkla** [comment]
I think it's a little weird if status chips with the same status do not always have the same color. There is one purple and one red "Konflikt" in the screenshot you posted.

**Comment by Steindt** [comment]
Fixed in #223
