### ISSUE TITLE
Använd de uppdaterade utskottsloggorna på t.ex utskottssidan

### ISSUE THREAD

**Issue by DagHemberg** [Dsek-LTH/web#367]
https://github.com/Dsek-LTH/grafik/tree/main/committee_logos

Tankar på hur detta kan funka från någon som inte kan webbutveckling;
- Servea från github direkt
- Cachea varje dag/timme/whatever serverside
- Ladda ner och uppdatera manuellt (usch)

**Comment by Isak-Kallini** [comment]
Jag tror att servea från github kan fungera bra, någon med access till grafik-repot behöver bara [enablea github pages](https://medium.com/@jeftachibiya360/how-to-host-images-for-your-website-on-github-a98d917284c5) i så fall. 
Cachea är nog också en bra idé

**Comment by Macludde** [comment]
Detta är done. bilden sparas som en url så la bara in url:n så det servas direkt från github. Finns stöd för dark, light, mono (bw.svg, så kan man ändra färg manuellt beroende på användningsområdet) och symbol.
#420
