### ISSUE TITLE
Date comparison for event creation does not work?

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#370]
![image](https://github.com/Dsek-LTH/web/assets/97372888/16d5e6ee-b871-4553-8921-6c6cf9d59ae1)

**Comment by fnurkla** [comment]
It seems this is because the default `recurringEndDatetime` in [the event creation schema](../../tree/main/src/routes/(app)/events/schema.ts) is always a week from the date _of creation_, instead of a week after the event's start date.

**Comment by fnurkla** [comment]
@Isak-Kallini I think you have a better grasp of how this works. Could you take a look at it?

**Comment by Isak-Kallini** [comment]
I'll look into it!
