### ISSUE TITLE
Updates are not synchronized with Keycloak

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#388]
- Mandates: Mandates should be synced with Keycloak, but it doesn't seem to work. Investigate!
- First and last names: when creating users, we get their first and last names from Keycloak. Then we store this information in our database and allow the user to edit the information. We should ensure the edits are sent to Keycloak as well so that the information stays up-to-date.

**Comment by Steindt** [comment]
Mandates seems to work locally with sandbox. Added so it updates name whenever user changes their name (#518).

**Comment by Isak-Kallini** [comment]
Syncing mandates seem to be broken still, no one in the Teknikfokus project group got their mandate synced

**Comment by Isak-Kallini** [comment]
It was not a problem on our side! The problem was groups being incorrectly nested in keycloak, for example `dsek.teknik.projgr.mdlm` was in the same subgroup as `dsek.teknik.projgr`, instead of being a subgroup of it
