### ISSUE TITLE
Add ability to subscribe to event calender

### ISSUE THREAD

**Issue by Macludde** [Dsek-LTH/web#425]
There should be a way to subscribe to the D-sek calender which is synced with the events on the site. Preferably any calender client (iCal and Google Cal are the top 2 I would say), but if only google cal is doable that's fine. TimeEdit works for both so I would guess it's doable.

I don't know how this is done but we had it on member-page so I would recommend checking that out!

**Comment by danieladugyan** [comment]
Done. It'll work for all calendars AFAIK since we use iCal which is a standard.
