### ISSUE TITLE
Fix issues with booking page

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#434]
KM mentioned some issues about the new booking page. Collect issues here, split up into tasks and resolve.

- [x] Members can't change their bookings
- [x] KM can't change members bookings
- [x] Members can't see what is booked
- [x] KM can't remove peoples bookings
- [x] Members can't remove booking

No longer applicable
- [ ] The calender view is broken. Everthing is in the same colour.
- [ ] Member can't view bookings by clicking on them on the calender.

**Comment by Macludde** [comment]
More issues:

- You can just see start time, no end time on bookis
- You can only see the "reason"/event name, not WHAT is booked
- You can't see who has booked something

**Comment by danieladugyan** [comment]
First release is up.
- The calendar is removed in favour of a simple table. 
- You can now delete bookings.

We should probably revisit the calendar, especially if people often need to see bookings other than their own, For now I think this is a quick and easy fix, you can at least see your own bookings clearly.

**Comment by danieladugyan** [comment]
Second release will be up soon. There's now a booking calendar that once again allows bookers to get a quick overview of what is booked and when. 

It's currently only showed on the booking creation page. This might be controversial, but I think it makes sense for its primary use case of finding a good time slot for your booking. It discourages using the booking system to just check whether something you want is booked or not, without actually making a booking request yourself.

Feel free to open new issues, but barring any major oversights I think this issues can be deemed resolved for now.
