### ISSUE TITLE
Error when trying to upload profile picture

### ISSUE THREAD

**Issue by alfredgrip** [Dsek-LTH/web#441]
Got following error when trying to upload a profile picture:
`JSON.parse: unexpected character at line 1 column 1 of the JSON data`
Not a very helpful error message 🤷‍♂️
The image was not corrupt or anything

<img width="612" alt="Screenshot 2024-08-21 at 10 28 28" src="https://github.com/user-attachments/assets/d4c08301-0e0e-4405-bb96-b9e24f883628">

**Comment by danieladugyan** [comment]
This seems to be caused by images that are too large. Investigate if that's true, and if so add a reasonable maximum image size with an error message if the image exceeds the maximum allowed size.

**Comment by danieladugyan** [comment]
Yes, nginx limits the size of images.

**Comment by 01ste02** [comment]
Minio has a larger file size-limit in our gateway. This needed to be increased for the website as well to allow uploading profile pictures through that route rather than directly to minio
