### ISSUE TITLE
Please fix booking site

### ISSUE THREAD

**Issue by philip-nielsen** [Dsek-LTH/web#444]
The booking site is nearly unusable at the moment. These are some of the issues right now: 
1. Members can't see what is booked
2. Members can't remove booking booking
3. I can't remove peoples bookings
4. Members can't change their bookings
5. I can't change members bookings
6. The calender view is broken. Everthing is in the same colour. 
7. Member can't view bookings by clicking on them on the calender.

**Comment by danieladugyan** [comment]
Moved to existing issue #434
