### ISSUE TITLE
Missing functionality when searching

### ISSUE THREAD

**Issue by IndigoWilke** [Dsek-LTH/web#533]
Would be nice to be able to use the up/down key to select people when searching on the site. 
It would also be great if you could view more results.

As it is now you have to click the person in question if you want to go to the person. Pressing enter only closes search. Also you can only see a certain amount of results as the ... at the bottom of the list is not tied to any functionality showing more results.

**Comment by danieladugyan** [comment]
We're working on an entirely new system for searching all sorts of content, not just members! Coming soon ™️
