### ISSUE TITLE
404 does not return 404

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#540]
### Description
When visiting a non-existing page, we show a 404 error but the HTTP response is 200 OK. I would expect the server to return a 404 for non-existing pages. This is more than just an annoyance since we have lots of web scrapers visiting dead links over and over again thinking that they still work.

### Steps to reproduce
1. Go to a non-existing page, i.e https://dsek.se/sektionen/km/boka.php.
2. View the status code, 200, in your browser's developer tools.

![Image](https://github.com/user-attachments/assets/52d12fff-bbc3-4022-ad41-3fbd75e528b1)

**Comment by Isak-Kallini** [comment]
After some investigation i found that it's because the data from `routes/(app)/+layout.server.ts` is streamed. The best way to solve this is probably making an error page outside `(app)`.
