### ISSUE TITLE
Lägg till en kategori/widget/whatever för årsspecifika dokument

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#549]
### Description

I sektionens verksamhet använder vi oss av olika årsspecifika dokument. Dessa inkluderar
- [verksamhetsplan](https://minio.api.dsek.se/documents/public/2023/HTM2/prop_verksamhetsplan_2024.pdf)
- [strategisk plan](https://minio.api.dsek.se/documents/public/2024/HTM1/Bilaga_Uppdatering_av_Strategisk_Plan.pdf)
- [rambudget](https://minio.api.dsek.se/documents/public/2023/HTM2/bilaga_rambudgeten_2024.pdf).

Just nu är dessa svåra att hitta: man måste in och leta bland möteshandlingarna (med undantag av den strategiska planen som av någon anledning ligger bland riktlinjerna).

Exempel på hur andra gör det:
E-sektionen:
<img src="https://github.com/user-attachments/assets/a1c1ff94-d320-4513-b3d7-f22d7cf047e5" alt="drawing" width="200"/>

Kåren:
![image](https://github.com/user-attachments/assets/7ada3136-5312-4107-8c67-4c8d75670efc)

### Describe the solution you'd like

En del av styrdokumentsidan där man kan se den nuvarande och de tidigare årgångarna av årsspecifika dokument.

> **Edit**: Eftersom dokumenten är svåra att hitta på något automatiskt sätt kan detta vara ett bra tillfälle att börja spara dokument som objekt i databasen. Jag tänker mig till exempel en dokumenttabell där varje rad är kopplad till någon fil i MinIO (via dess relativa sökväg, dvs path). Då får vi möjlighet att lägga till "metadata" för varje dokument, t.ex vilket slags dokument det är, vilket år dokumentet är från osv.
// @danieladugyan 

### Describe alternatives you've considered

Man skulle kunna ha en separat sida för de årsspecifika dokumenten, men jag kan tycka att det är lite overkill. Hellre i så fall att man har olika [flikar](https://daisyui.com/components/tab/) i styrdokumentsidan, IMO.

**Comment by danieladugyan** [comment]
Känns väldigt rimligt! Den enda svårigheten är att hitta något smidigt sätt att söka upp alla dokument i deras respektive mappar. Som du säger ligger dokumenten just nu lite huller om buller.

**Comment by fnurkla** [comment]
Ja, det arbetet måste man ju göra oavsett liksom: alla gamla verksamhetsplaner måste letas upp osv.

Jag undrar om vi inte kan komma på ett bättre system för dokument allmänt? Jag tycker att F-sektionens system där alla dokument får ett nummer har sina fördelar. Då får liksom alla dokument ett "diarienummer".
