### ISSUE TITLE
Val-page for showing nominations

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#558]
### Description

KTH has a page where all nominations for positions are published. You can see who has been nominated and for what position an whether they have accepted their nomination. It would be nice if we had something similar, particularly for HTM-val where there are so many open positions.

Originally proposed by @cgertner

### Describe the solution you'd like

KTH's page is nice: https://val.datasektionen.se/

### Describe alternatives you've considered

Currently this information is made public through a Google Spreadsheet. You can see who has been nominated and for what, but not whether they have accepted their nomination. If members could see that people have turned down their nominations they might be more inclined to apply for a position, since they get a more accurate sense of their "competition".

**Comment by DagHemberg** [comment]
Having the page show whether or not you have accepted your nomination isn't possible if we want to adhere to Policy för valberedningsarbete (_Policy for nomination proceedings_):

```
3 Sekretess och etik

Valberedningens intervjuer sker i förtroende och är sekretessbelagda. Valberedningens 
medlemmar får ej delge denna information utanför valberedningen. [...]
```

translated (_unofficial interpretation_):

```
3 Privacy and ethics

The interviews held by the Nominations Committee transpire in confidence and are 
confidential. Members of the Nominations Committee may not share this information 
outside the Nomination Committee. [...]
```

Accepting your nomination equates to booking a slot for an interview, and so publicizing this info would in turn mean breaking confidence and be in direct violation of the policy.

**Comment by anahitachavan** [comment]
This almost certainly is against policy. The nominations may be public but we may not publicly announce who has and hasn't been interviewed and we may only display the number of interviewees as an interval. 

That said, as this concerns elections that take place at guild meetings, and are therefore far more public than other elections at the guild, it can be worth discussing whether we need anonymity during the nomination process, but this is not a topic for DWWW.

**Comment by danieladugyan** [comment]
Closing due to comments from @DagHemberg and @anahitachavan. Feel free to open if circumstances changes.
