### ISSUE TITLE
Sjungbok -> Sångbok

### ISSUE THREAD

**Issue by LeonIngman** [Dsek-LTH/web#559]
### Description

Det står för tillfället Sjungbok på hemsidan, men tänker att det borde vara Sångbok, **Sångförman**. 

### Describe the solution you'd like

Ändra på relevanta ställen från Sjungbok till Sångbok

**Comment by danieladugyan** [comment]
InfA and vice InfA approve ✅

**Comment by alfredgrip** [comment]
@danieladugyan @DagHemberg @anahitachavan

**Comment by fgren** [comment]
(Jag mergade utan att se kommentaren, därför är issuen öppen igen.)
Noterar att båda apparna på gamla sidan heter Sångbok, och det står Sångbok på den fysiska boken. Vilket använder vi numera?

**Comment by alfredgrip** [comment]
Officiellt finns det inget beslut att "den här använder vi", och att den heter "sjungbok" är inte särskilt välkänt på sektionen heller.

> Noterar att båda apparna på gamla sidan heter Sångbok, och det står Sångbok på den fysiska boken. Vilket använder vi numera?

Jo det är sant, men rubriken på sidan heter "Den mobila sjungboken" och i andra stycket kan man läsa "...trädens rätt att inte bli sjungböcker så finns det tack och lov medlemmar...". Dessutom förekommer "sjungbok" många fler gånger i appens repo: https://github.com/FredrikFolkesson/D-Sek-Sjungbok

Personligen tycker jag detta är en löjlig, men rolig och studentikos grej. Att aktivt ersätta "sjungbok" med "sångbok" är (enligt mig) att medvetet ta bort en del av vår historia och traditioner, vilket jag tycker är synd.

**Comment by fgren** [comment]
#617 , nu ändrat till Sångarkiv.
