### ISSUE TITLE
Add new page for showing open positions

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#621]
The landing page for logged out users has a big call-to-action button with the text "Get involved".
- Upon clicking the button, we should show currently available positions in the guild.
- Positions that are always available could be pinned to the top.
- Easiest implementation (in terms of code and usability for authors) could be to base this feed on the news feed. Use tags or something similar to filter out news articles relevant to open committee positions.

Original design inspiration: https://github.com/Dsek-LTH/web/assets/26229521/c35aa5ab-2ccd-4e55-b06a-56fb9abcea46
New design inspiration:

![image](https://github.com/user-attachments/assets/afb9abbe-e011-4f29-9094-8370421b9e01)

**Comment by danieladugyan** [comment]
Follow up: I made a quick draft in Figma. I'm thinking this is something we could conceivably develop in an evening or so and launch quickly. There are lots of open positions at the moment so it would be awesome if we could get something up and running now.

Idea for database schema:
| id | committee_id | markdown          | markdown_en | link          | created_at |
|----|--------------|-------------------|-------------|---------------|------------|
| 1  | aktu         | - d-sportare, ... | ...         | forms.gle/... | 2024-12-03 |
| 2  | cafe         | ...               | ...         | ...           | 2024-12-04 |
| 3  | infu         | ...               | ...         | ...           | 2023-12-05 |

![image](https://github.com/user-attachments/assets/afb9abbe-e011-4f29-9094-8370421b9e01)

**Comment by fgren** [comment]
Some committees (like InfU) has separate forms for the positions (and some don't), how do we handle this?
