### ISSUE TITLE
Expenses: borders hard to see in light mode

### ISSUE THREAD

**Issue by erik-stein** [Dsek-LTH/web#647]
### Description

White border is hard to see on grey background
![2024-12-11T16:10:18,543240156+01:00](https://github.com/user-attachments/assets/14748b77-7c10-4576-b835-ad8b4f6a2985)

### Steps to reproduce

1. Go to https://www.dsek.se/expenses/1
2. Change to light mode
3. Squint to see the border

**Comment by Macludde** [comment]
solved in #645
